source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NBULogStub_Example', :exclusive => true do
  pod "NBULogStub", :path => "../"
end

target 'NBULogStub_Tests', :exclusive => true do
  pod "NBULogStub", :path => "../"

  
end
